# Generated by Django 3.0 on 2020-02-01 11:43

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=10)),
                ('issue', models.TextField(max_length=5000)),
            ],
        ),
    ]
